Content
Draiking/Verstka2 pull request #3
Opened 2018-12-20 21:08 UTC by Draiking

Закончил работу над 4 секциями

2018-12-21 15:23 UTC, Gordondalos requested changes

2018-12-21 15:23 UTC, Gordondalos commented on src/js/common.js
> +	$(".section-content .info-item").equalHeights();
разгугли и напиши коментраий к каждой строке

2018-12-21 15:23 UTC, Gordondalos commented on src/parts/content/content.html
> +<section class="homesect section_1">
файл слишком длинный нужно было разделить на части,
section_1 нужно было написать section-1 чтобы везде был один стиль

2018-12-21 15:23 UTC, Gordondalos commented on src/parts/content/content.html
> +                <div class="col-sm-8 info-item-wrap">
судя по коду тут проблемы с адаптивностью, не вижу чтобы под мобилку изменялись на col-xs-12, таких классов много

2018-12-21 15:23 UTC, Gordondalos commented on src/parts/content/content.html
> +        <div class="s1_bottom_triangle">
существует стили написания кода camelCase - это верблюжья нотация - это когда каждое новое слово с большой буквы,
snake_case - это змеевидная нотация когда символ подчеркивания снизу и код похож на змею, kebab-case - это как шашлычная палочка все через тире. В html принято kebab-case или змеиная нотация когда используется бем методология нейминга (это от яндекса), и если у тебя нет бема в коде лучше писать только кебаб. Писать часть стилей в одном часть в другом это дурной тон, и про тебя будут думать что ты неряха.

2018-12-21 15:23 UTC, Gordondalos commented on src/parts/content/content.html
> +        <div class="s2-items">
названия нужно писать осмысленные, чтобы было понятно что это такое, я конечно догадаюсь что это s-wrap это какой то враппер (обертка) но вот над чем она мне никак не понятно и это плохо что за класс s2-items неясно

2018-12-21 15:23 UTC, Gordondalos commented on src/parts/content/content.html
> +
секции надо было в отдельные файлы

2018-12-21 15:23 UTC, Gordondalos commented on src/parts/content/content.scss
> +.s_dark{
что за повторение класса по 50 раз , ты же scss переделай так чтобы s_dark  был один а у него было много детей

2018-12-21 15:23 UTC, Gordondalos commented on src/parts/content/content.scss
> +/* Конец 3 секции */
чтоб вот так не делать каждую секцию в отдельный файл

2018-12-21 15:23 UTC, Gordondalos commented on src/parts/content/content.scss
> +
не должно быть больше 2-х строк пробелов

2018-12-21 15:23 UTC, Gordondalos commented on src/style/main.min.scss
> +@import "../parts/content/content";
также нужно было в контент подключить каждую секцию и дать ей осмысленное название

2018-12-21 15:23 UTC, Gordondalos commented on src/style/media.scss
медиазапросы если их много лучше в отдельный файл

2018-12-21 15:23 UTC, Gordondalos commented on src/style/media.scss
>  /* Custom, iPhone Retina */
пустые классы и медиазапросы нужно удалять, чтобы не вспоминать как оно пишется, можно сделать снипеты для медиа-запросов, если не знаешь как спроси у меня

2018-12-24 13:53 UTC, Draiking commented on src/js/common.js
> +	$(".section-content .info-item").equalHeights();
сделано

2018-12-24 13:53 UTC, Draiking commented on src/parts/content/content.html
> +<section class="homesect section_1">
сделано

2018-12-24 14:57 UTC, Gordondalos approved these changes

2018-12-24 15:15 UTC, merged