Content
Draiking/Verstka2 pull request #5
Opened 2018-12-29 07:05 UTC by Draiking

Закончил работу над контентом

2018-12-29 17:22 UTC, Gordondalos requested changes
все поправить !

2018-12-29 17:22 UTC, Gordondalos commented on src/parts/content/section4.scss
> +.s-gray {
ты все делаешь правильно, сохраняя иерархию в scss, но большую вложенность трудно поддерживать
и вложенность более 3-х уровней считается дурным тоном. Перепиши так чтобы уровней было 2 максимум 3, при этом уровень секции это первый уровень.

2018-12-29 17:22 UTC, Gordondalos commented on src/parts/content/section4.scss
> +.section-4 {
вот такого вообще быть не должно, селектор секции указывается один раз в начале файла, и потом все теги вложены в него, перепиши по нормальному

2018-12-29 17:22 UTC, Gordondalos commented on src/parts/content/section4.scss
> +    &:before {
вот тот случай когда тебе нужен третий уровень это псевдо селекторы, в остальных случаях тебе достаточно 2.
тебе дай волю так ты тут все дерево повторишь для каждого тега, в результате получится много лишнего кода.

2018-12-29 17:22 UTC, Gordondalos commented on src/parts/content/section4.scss
> +      display: none;
нужно привыкать и использовать классы бутстрапа, тебе фреймворк не просто так дали, твоя задача использовать уже готовые классы чем использовать свои, если возможно то display: none можно быдло указать клсаом .d-none  в html

2018-12-29 17:22 UTC, Gordondalos commented on src/parts/content/section4.scss
>  .s-gray {
вверху я уже видел s-gray, почему он опять тут, все стили одного класса должны быть в одном месте, не нужно лишних повторений, только в том случае если ты их переопределяешь его можно написать еще раз, и это можно сделать только в медиа запросах

2018-12-29 17:22 UTC, Gordondalos commented on src/parts/content/section5.scss
>    font-family: PFCentroSlabProMedium;
если можно не указывать фонт фемели то нужно не указывать, вероятно он возьмет от родителя

2018-12-29 17:22 UTC, Gordondalos commented on src/parts/content/section5.scss
>    text-align: center;
есть такой класс бутстрапа

2018-12-29 17:22 UTC, Gordondalos commented on src/parts/content/section5.scss
>    font-size: em(19px);
вот такого кода быть не должно это не валидный код, или уж в пикселях или в em, надо как то определиться

2018-12-29 17:22 UTC, Gordondalos commented on src/parts/content/section5.scss
> +    path {
сомневаюсь что у тебя есть тег path

2018-12-29 17:22 UTC, Gordondalos commented on src/parts/content/section6.html
> +    <div class="section-pb">
опять бессмысленное название, по хорошему ты должен использовать классы бутстрапа и их тебе должно быть достаточно, дополнительные классы можно задавать чтобы повысить семантику и понятность кода, чтобы было ясно что это за компонент или элемент section-pb это вообще не понятно.

По хорошему ты мог указать только название секции, и скажем карточки или какие то под блоки по семантике. больше лишних классов тебе не нужно, чем больше классов тем хуже. У тебя есть родительский селектор, и может быть несколько селекторов для пониманя какой блок ты правишь, дальше ты можешь использовать вложенные или сдвоенные селекторы

2018-12-29 17:22 UTC, Gordondalos commented on src/parts/content/section6.html
> +                    <div class="team team-off team-on">
вот тут либо team-off либо team-on должно быть переделай так чтобы был или тот или иной класс, как я понимаю ты манипулируешь ими при помощи jquery, он должен один класс добавлять. Сейчас у тебя имеет приоритет тот который написан ниже в ксс

2018-12-29 17:22 UTC, Gordondalos commented on src/parts/content/section6.scss
> +    @extend .cards;
в реальном коде писать экстенды не очень хорошо, ты должен понимать что они значат и как работают чтобы разобраться в чужом коде, сам лучше воздержись, во первых у тебя изоляция не должна это позволять, во вторых так получается очень много лишнего кода, я тебе показывал какой получается билд при экстендах - он делает очень много кода, это плохо. еще более печально что cards есть такие классы у бутстрапа, сейчас вместо этих пары строк в конечном файле сгенерировалалось строк 200, это грустно, проще было закописастить. И если тебе придется изменить порядок импорта, утебя вся верстка ляжет

2018-12-29 17:22 UTC, Gordondalos commented on src/parts/content/section6.scss
> +.s-gray {
да еще по 2-3 раза одно и тоже и по 5 вложенностей - ужас

2018-12-29 17:22 UTC, Gordondalos commented on src/parts/content/section6.scss
> +  font-size: em(22px);
про это писал выше не делай так, если хочется чтобы шрифты были консистентными в проекте, нужно определить типографику, сделать заготовку по размеру шрифтов от f10 до f32 и ее использовать, и тогда можно эти классы указывать только в html, тут не должно быть размеров, если очень хочется то тут могут быть переменные как для цветов

2018-12-29 17:22 UTC, Gordondalos commented on src/parts/content/section6.scss
> +  margin-top: 15px;
используй классы бутстрапа для таких отступов.
по хорошему все маржины и падинги до 30 пикселей есть в бутстрапе назваются они спейсингами гугли , читай и не пиши больше отступы в scss

2018-12-29 17:22 UTC, Gordondalos commented on src/parts/content/section6.scss
> +    perspective: 600px;
это вероятно не стандартное свойство, если можно сделать по другому то лучше сделать, найди поддерживаемость этого свойства и приложи мне сюда в коментарии ссылку на пооддержку браузерами

2018-12-29 17:22 UTC, Gordondalos commented on src/parts/content/section7.scss
> +.section-7 {
здесь те же ошибки - исправить все что и в 4-5 секциях, сделай до 3-х уровней

2018-12-29 17:22 UTC, Gordondalos commented on src/parts/content/section7.scss
> +        transform: translate3d(200px, 0, 0);
найди и приложи что означают тут параметры

2018-12-29 17:22 UTC, Gordondalos commented on src/parts/content/section7.scss
> +        transition: all .7s ease;
и тут укажи параметры, что означают

2018-12-29 17:22 UTC, Gordondalos commented on src/parts/content/section7.scss
> +      .slide-descr, h3, p {
не делай так используй скобки

2018-12-29 17:22 UTC, Gordondalos commented on src/parts/content/section7.scss
> +        box-shadow: 0 0 0 7px $main-color;
прогугли тут свойства теней что означают параметры

2018-12-29 17:22 UTC, Gordondalos commented on src/style/colors.scss
> +$color-sec-5: #6e7b8b;
по переменной должно быть понятно какого она цвета, сделай рефакторинг и переименуй

2018-12-30 08:04 UTC, Draiking commented on src/parts/content/section5.scss
> +    path {
используется на svg

2019-01-07 08:49 UTC, Draiking commented on src/parts/content/section4.scss
> +    &:before {
понял

2019-01-08 21:54 UTC, Draiking commented on src/parts/content/section4.scss
> +.s-gray {
исправил

2019-01-08 21:54 UTC, Draiking commented on src/parts/content/section4.scss
> +.section-4 {
исправил

2019-01-08 21:54 UTC, Draiking commented on src/parts/content/section4.scss
> +      display: none;
такой возможности нет

2019-01-08 21:55 UTC, Draiking commented on src/parts/content/section4.scss
>  .s-gray {
исправил

2019-01-08 21:59 UTC, Draiking commented on src/parts/content/section7.scss
> +      .slide-descr, h3, p {
исправил

2019-01-08 22:04 UTC, Draiking commented on src/parts/content/section7.scss
> +        transform: translate3d(200px, 0, 0);
написал

2019-01-08 22:09 UTC, Draiking commented on src/parts/content/section7.scss
> +        transition: all .7s ease;
сделал

2019-01-08 22:10 UTC, Draiking commented on src/parts/content/section7.scss
> +        box-shadow: 0 0 0 7px $main-color;
хорошо

2019-01-09 18:30 UTC, Draiking commented on src/style/colors.scss
> +$color-sec-5: #6e7b8b;
исправил

2019-01-09 18:31 UTC, Draiking commented
все исправил

2019-01-10 16:23 UTC, Draiking commented
все исправил

2019-01-10 16:25 UTC, merged